<a href="https://colab.research.google.com/github/blabossiere/cap-comp215/blob/main/Comp_215_Lab_7_Rough_Work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy.signal import correlate2d

#  print("random number:", np.random.choice([0, 1], (3,3), p = (1-self.p, self.p)))

#         number_list = []

#         count = 0
#         for row in self.state:
#           for number in row:
#             number_list.append(number)
#             count = count + 1
#         #assert(int(self.state[1][0] == 0))
#         #self.state[0][1] = 1
#         print(type(number_list[0]))
#         print("number count:", count)
#         print("number list", number_list)

#         size = int(math.sqrt(count))
#         print(size)

#         row_index = 0
#         for row in self.state:
#           for number in row:
#             if row[number] == 0:
#               self.state[row][row_index] = np.array([1])
              #print(self.state[row][row_index])
          # row_index = row_index + 1
            #self.state[row][row_index] = np.random.choice([0, 1], (1,1), p = (1-self.p, self.p))
              #self.state[row][number] = 1
              # number = np.random.choice([0, 1], (1,1), p = (1-self.p, self.p))
              # self.state[row][number] = number

        # self.state[0][0] = np.random.choice([0, 1], p = (1-self.p, self.p))
        # self.state[0][1] = np.random.choice([0, 1], p = (1-self.p, self.p))
        # self.state[0][2] = np.random.choice([0, 1], p = (1-self.p, self.p))
        # self.state[1][0] = np.random.choice([0, 1], p = (1-self.p, self.p))
        # self.state[1][1] = np.random.choice([0, 1], p = (1-self.p, self.p))
        # self.state[1][2] = np.random.choice([0, 1], p = (1-self.p, self.p))
        # self.state[2][0] = np.random.choice([0, 1], p = (1-self.p, self.p))
        # self.state[2][1] = np.random.choice([0, 1], p = (1-self.p, self.p))
        # self.state[2][2] = np.random.choice([0, 1], p = (1-self.p, self.p))

        # count = 0
        # for row in self.state:
        #   for number in row:
        #     count = count + 1
        # size = int(math.sqrt(count))
        # self.count = int(count)
        # self.size = size

In [ ]:
q = 0.5

array1 = np.random.choice([0, 1], (4, 4), p=[q, 1 - q])
#print(array1)

array2 = np.array([             # set the state matrix to a known value for testing with
                  [1, 5, 5],
                  [1, 5, 5],
                  [1, 1, 5],

])

print(array2)

kernel = np.array([[0, 1, 0],
                   [1, 0, 1],
                   [0, 1, 0]])

array3 = correlate2d(array2, kernel, mode='same')
print(array3)

# % is remainder
# // is double divider.

print(5//3)
print(5%3)

print(type(11%5))

print(array2[0][0] % 5)
print(array2[0][0] // 5)

            #if self.state[row][row_index] == 1 and self.state3[row][row_index] == 5: # Rule 4
            # if self.state3[row][row_index] >= 5 and self.state[row][row_index] == 1:
            # if (self.state3[row][row_index] % 5) == 1 and self.state[row][row_index] == 1:
            #   self.state2[row][row_index] = 5
        """and self.state[row][row_index] == 1:"""
              # if (row + 1) < self.n:
              #   self.state2[row + 1][row_index] = 5
              # if (row - 1) > 0:
              #   self.state2[row - 1][row_index] = 5
              # if (row_index + 1) < self.n:
              #   self.state2[row][row_index + 1] = 5
              # if (row_index - 1) > 0:
              #   self.state2[row][row_index - 1] = 5

#y_list.append(ian.pct_occupied())

#for i in range(ian_animator.frames):
  #y_list.append(ian.pct_occupied())
#ian_animator.animate()

# if ian_animator.step > 0:

[[1 5 5]
 [1 5 5]
 [1 1 5]]
[[ 6 11 10]
 [ 7 12 15]
 [ 2 11  6]]
1
2
<class 'int'>
1
0
