<a href="https://colab.research.google.com/github/blabossiere/cap-comp215/blob/main/Computer_215_Lab_6_Rough_Work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from scipy.signal import correlate2d

a = np.random.randint(2, size = (10, 10), dtype=np.uint8)
print(a)

ca = np.random.randint(2, size = (1, 10), dtype=np.uint8)
print(ca)

b = np.zeros_like(a)
rows, cols = a.shape

[[1 1 0 0 1 1 0 0 1 1]
 [1 1 0 0 0 0 1 1 1 1]
 [0 1 1 0 0 1 1 0 1 1]
 [0 1 1 0 0 0 1 0 1 0]
 [1 1 1 1 1 1 0 1 0 0]
 [1 0 1 0 1 0 1 1 0 1]
 [1 1 1 1 0 0 0 1 0 0]
 [0 1 0 1 1 1 0 1 0 1]
 [1 1 1 0 0 0 1 1 1 1]
 [1 0 0 1 0 1 0 1 1 0]]
[[0 0 1 0 0 1 1 0 0 1]]


In [3]:
kernel = np.array([[1, 1, 1],
                  [1, 10, 1],
                   [1, 1, 1]])

c = correlate2d(a, kernel, mode='same')
print(c)

b = (c==3) | (c==12) | (c==13)
b = b.astype(np.uint8)

b = (c==3) | (c==12) | (c==13)
b = b.astype(np.uint8)

table = np.zeros(20, dtype=np.uint8)
print(table)
#table[[0, 10, 19]] = 2
#print(table)
table[[3, 12, 13]] = 1
print(table)
c = correlate2d(a, kernel, mode='same')
b = table[c]
print(b)

[[13 13  2  1 11 12  3  4 14 13]
 [14 15  4  2  3  5 14 15 16 15]
 [ 4 15 14  2  1 13 14  7 15 14]
 [ 4 16 16  5  4  5 14  5 13  3]
 [13 16 15 15 13 14  5 14  4  2]
 [14  8 16  7 14  4 14 13  4 10]
 [13 15 15 15  5  4  5 13  5  2]
 [ 5 16  7 14 13 12  5 14  6 12]
 [13 14 14  4  5  4 15 15 16 13]
 [12  4  3 11  2 11  4 14 14  3]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0]
[[1 1 0 0 0 1 1 0 0 1]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1]
 [1 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 1 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 1]]
