<a href="https://colab.research.google.com/github/blabossiere/cap-comp215/blob/main/Computer_215_Lab_6_Rough_Work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from scipy.signal import correlate2d

a = np.random.randint(2, size = (10, 10), dtype=np.uint8)
print(a)

ca = np.random.randint(2, size = (1, 10), dtype=np.uint8)
print(ca)

b = np.zeros_like(a)
rows, cols = a.shape

[[0 1 1 1 0 0 0 1 1 0]
 [1 1 0 0 1 0 1 1 0 1]
 [1 0 1 1 1 1 1 1 0 1]
 [0 0 1 0 1 0 1 0 1 0]
 [1 0 0 1 0 1 1 0 0 1]
 [1 0 0 1 0 0 1 1 0 0]
 [1 1 0 0 1 0 1 0 1 0]
 [0 0 0 0 1 0 1 1 1 0]
 [0 1 1 1 1 1 0 1 1 1]
 [1 0 0 1 1 0 0 0 1 0]]
[[1 1 0 0 0 0 1 0 1 1]]


In [4]:
kernel = np.array([[1, 1, 1],
                  [1, 10, 1],
                   [1, 1, 1]])

c = correlate2d(a, kernel, mode='same')
print(c)

b = (c==3) | (c==12) | (c==13)
b = b.astype(np.uint8)

b = (c==3) | (c==12) | (c==13)
b = b.astype(np.uint8)

table = np.zeros(20, dtype=np.uint8)
print(table)
#table[[0, 10, 19]] = 2
#print(table)
table[[3, 12, 13]] = 1
print(table)
c = correlate2d(a, kernel, mode='same')
b = table[c]
print(b)

[[ 3 13 13 12  2  2  3 13 13  2]
 [13 15  6  6 14  5 15 15  6 12]
 [12  5 13 15 14 16 15 15  5 12]
 [ 2  4 13  6 15  7 15  5 13  3]
 [11  3  3 13  4 14 14  5  3 11]
 [13  4  3 12  4  5 14 14  3  2]
 [12 12  2  3 12  5 14  7 13  2]
 [ 3  4  4  5 14  6 14 16 15  4]
 [ 2 12 13 15 15 14  4 15 15 13]
 [11  3  4 14 14  3  2  3 13  3]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0]
[[1 1 1 1 0 0 1 1 1 0]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 1 1]
 [0 1 1 1 0 0 0 0 1 0]
 [1 0 1 1 0 0 0 0 1 0]
 [1 1 0 1 1 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 1]
 [0 1 0 0 0 1 0 1 1 1]]


In [5]:
p = 0.5

random_array = np.random.choice((0,1), size = (5, 5), p = (1-p, p))
print(random_array)

[[0 1 0 0 0]
 [0 1 0 1 1]
 [1 0 0 1 1]
 [1 0 1 1 0]
 [1 1 0 1 1]]


In [38]:
# Ex. 2 experimental setup

# class BetterLife2D(Life2D):
#     """ Improvements on the basic Life2D model """

#     def __init__(self, n_rows, n_cols):

#       self.n_rows = n_rows
#       self.n_cols = n_cols

#     def randomize_state(self, p):
#         """ Randomize the state of this GoL, where probability of a "live" cell is p """
#         # Ex. 2 your code here...
#         random_array = np.random.choice([0,1], size = (self.n_rows, self.n_cols), p = (1-p, p))
#         print(random_array)
#         #return random_array


# def random_life(p, n_rows, n_cols):
#     """ Return a Life2D object of given dimensions with initial randomized state where "live" cells have probability p """
#     # Ex. 2 your code here...
#     random_array2 = BetterLife2D.randomize_state(owen, p)
#     return random_array2

# # Test Cases

# owen = BetterLife2D(10, 10)
# model = owen.randomize_state(0.5)

# random_life(0.5, owen.n_rows, owen.n_cols)

array1 = [0, 0, 0]

array2 = np.random.choice((1,1), (4, 4))
print(array1)
print(array2)

(array2[0][0:3]) = array1

print(array2)

massive_array = np.zeros(shape=(26, 26), dtype=np.uint8)
#print(massive_array)
for i in range(26):
  massive_array[i][i] = 1
print(massive_array)

[0, 0, 0]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 