<a href="https://colab.research.google.com/github/blabossiere/cap-comp215/blob/main/Computer_215_Lab_6_Rough_Work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.signal import correlate2d

a = np.random.randint(2, size = (10, 10), dtype=np.uint8)
print(a)

ca = np.random.randint(2, size = (1, 10), dtype=np.uint8)
print(ca)

b = np.zeros_like(a)
rows, cols = a.shape

[[0 0 0 1 1 1 1 0 0 0]
 [1 0 1 0 1 1 1 1 0 1]
 [1 0 0 1 1 1 0 1 0 1]
 [0 0 0 0 1 0 0 0 0 1]
 [0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 1 0 0 1 0 0]
 [1 1 1 1 1 0 0 0 0 0]
 [1 0 1 1 0 1 0 0 0 1]
 [0 1 0 0 0 1 1 1 1 0]
 [0 1 1 0 1 1 1 1 0 1]]
[[1 1 1 0 1 0 1 1 0 0]]


In [2]:
kernel = np.array([[1, 1, 1],
                  [1, 10, 1],
                   [1, 1, 1]])

c = correlate2d(a, kernel, mode='same')
print(c)

b = (c==3) | (c==12) | (c==13)
b = b.astype(np.uint8)

b = (c==3) | (c==12) | (c==13)
b = b.astype(np.uint8)

table = np.zeros(20, dtype=np.uint8)
print(table)
#table[[0, 10, 19]] = 2
#print(table)
table[[3, 12, 13]] = 1
print(table)
c = correlate2d(a, kernel, mode='same')
b = table[c]
print(b)

[[ 1  2  2 13 14 15 14  3  2  1]
 [11  3 12  6 17 17 16 13  4 11]
 [11  3  2 14 15 15  5 12  5 12]
 [ 1  1  2  4 15  5  4  3  5 13]
 [ 0  0  1 12  4 13 12  3 13 12]
 [ 2  3  4  5 14  4  3 12  3  2]
 [12 14 14 15 14  3  2  1  2  1]
 [13  6 15 14  5 13  4  3  3 11]
 [ 3 14  5  4  5 15 16 14 14  3]
 [ 2 12 12  2 12 14 15 14  4 11]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0]
[[0 0 0 1 0 0 0 1 0 0]
 [0 1 1 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 1 0 1]
 [0 0 0 1 0 1 1 1 1 1]
 [0 1 0 0 0 0 1 1 1 0]
 [1 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 1 0 1 1 0]
 [1 0 0 0 0 0 0 0 0 1]
 [0 1 1 0 1 0 0 0 0 0]]


In [4]:
p = 0.5

random_array = np.random.choice((0,1), size = (5, 5), p = (1-p, p))
print(random_array)

[[1 1 1 0 0]
 [1 0 1 0 1]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [1 1 1 0 0]]


In [ ]:
# Ex. 2 experimental setup

class BetterLife2D(Life2D):
    """ Improvements on the basic Life2D model """

    def __init__(self, n_rows, n_cols):

      self.n_rows = n_rows
      self.n_cols = n_cols

    def randomize_state(self, p):
        """ Randomize the state of this GoL, where probability of a "live" cell is p """
        # Ex. 2 your code here...
        random_array = np.random.choice([0,1], size = (self.n_rows, self.n_cols), p = (1-p, p))
        print(random_array)
        #return random_array


def random_life(p, n_rows, n_cols):
    """ Return a Life2D object of given dimensions with initial randomized state where "live" cells have probability p """
    # Ex. 2 your code here...
    random_array2 = BetterLife2D.randomize_state(owen, p)
    return random_array2

# Test Cases

owen = BetterLife2D(10, 10)
model = owen.randomize_state(0.5)

random_life(0.5, owen.n_rows, owen.n_cols)